services:
  - type: web
    name: mopcare-gateway
    runtime: go
    buildCommand: cd gateway-fiber && go build -o app
    startCommand: cd gateway-fiber && ./app
    envVars:
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_PROJECT_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GATEWAY_PORT
        value: "9090"