services:
  - type: web
    name: go-gin-app
    runtime: go
    buildCommand: go build -o app
    startCommand: ./app
    envVars:
      - key: SUPABASE_DB_URL
        fromDatabase:
          name: supabase-db
          property: connectionString